<Project Sdk="Aspire.AppHost.Sdk/13.4.2">

  <ItemGroup>
    <ProjectReference Include="..\DocumentManagementMicroservices.IdentityService\DocumentManagementMicroservices.IdentityService.csproj" />
    <ProjectReference Include="..\DocumentManagementMicroservices.DocumentService\DocumentManagementMicroservices.DocumentService.csproj" />
    <ProjectReference Include="..\DocumentManagementMicroservices.ApiGateway\DocumentManagementMicroservices.ApiGateway.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>29fb564b-b1ad-4efc-adf6-48b731600cac</UserSecretsId>
  </PropertyGroup>

</Project>
