<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc" Version="10.0.0" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="10.0.0" />
    <PackageReference Include="Aspire.MongoDB.Driver" Version="13.4.2" />
    <PackageReference Include="Aspire.StackExchange.Redis.DistributedCaching" Version="13.4.2" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.2.2" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
    <PackageReference Include="MongoDB.Driver" Version="3.9.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.14.14" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DocumentManagementMicroservices.ServiceDefaults\DocumentManagementMicroservices.ServiceDefaults.csproj" />
    <ProjectReference Include="..\DocumentManagementMicroservices.BuildingBlocks\DocumentManagementMicroservices.BuildingBlocks.csproj" />
  </ItemGroup>

</Project>
